//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("projectquery", Namespace="", IsNullable=false)]
public partial class projectqueryType {
    
    private queryType[] queryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("query", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public queryType[] query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryType {
    
    private string querynameField;
    
    private string queryinfoField;
    
    private string additionalqueryinfoField;
    
    private queryTypeParsemethod parsemethodField;
    
    private bool replacetodayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string queryname {
        get {
            return this.querynameField;
        }
        set {
            this.querynameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string queryinfo {
        get {
            return this.queryinfoField;
        }
        set {
            this.queryinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string additionalqueryinfo {
        get {
            return this.additionalqueryinfoField;
        }
        set {
            this.additionalqueryinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public queryTypeParsemethod parsemethod {
        get {
            return this.parsemethodField;
        }
        set {
            this.parsemethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool replacetoday {
        get {
            return this.replacetodayField;
        }
        set {
            this.replacetodayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum queryTypeParsemethod {
    
    /// <remarks/>
    resolvelist,
    
    /// <remarks/>
    tasklist,
    
    /// <remarks/>
    urlist,
    
    /// <remarks/>
    tasktable,
    
    /// <remarks/>
    urtable,
    
    /// <remarks/>
    createresolve,
}
